package cmd

import pf "github.com/Bookshelf-Writer/PointerFactory"

var wp = pf.CreateWrapper()

var flagsBuf = flagObj{}
var errMAP = map[string]bool{}
var isValid = false

func init() {
	isValid = true

	flagsBuf.jsonFormat.info.addInfo("json", "Mode of operation in json-format")
	flagsBuf.ver.info.addInfo("ver", "Information on assembly")

	flagsBuf.printTypes.info.addInfo("types", "Print all available pointer types")
	flagsBuf.validType.info.addInfo("type", "Check if it is a valid type")

	flagsBuf.createPointer.info.addInfo("crt", "Mode of UID creation")
	flagsBuf.setType.info.addInfo("t", "Set type")
	flagsBuf.setServer.info.addInfo("s", "Set server")
	flagsBuf.setPointer.info.addInfo("p", "Set pointer")

	flagsBuf.setDateTime.info.addInfo("d", "Create UID by date (ISO 8601)")
	flagsBuf.setCount.info.addInfo("c", "Number of UIDs generated by date (default 1)")

	flagsBuf.validString.info.addInfo("str", "Enter UID (check for correctness)")
	flagsBuf.printInfo.info.addInfo("i", "Detailed information about UID")

	initHelpArr()
}
